[tool.poetry]
name = "lightsoff-api"
version = "0.1.0"
description = "The API used by lightsoff website"
authors = ["Alexandre Papin <alexandre.papin@indaclouds.fr>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"

Flask = "2.2.2"
Flask-Migrate = "3.1.0"
flask-openapi3 = "2.1.1"
flask-sqlalchemy = "3.0.2"
psycopg2 = "2.9.4"
zappa = "0.55.0"

[tool.poetry.dev-dependencies]
black = "22.10.0"
pytest = "7.1.3"
python-dotenv = "0.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
